version: '3.1'

networks:
  loki:

volumes:
  genhub:

services:
  db:
    image: postgres:15.1
    restart: always
    ports:
      - 5432:5432
    volumes:
      - genhub:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    shm_size: 1g

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
