import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :not_spotify, NotSpotifyWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: NotSpotify.Finch

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

config :not_spotify, NotSpotify.Repo,
  url: System.get_env("DATABASE_URL"),
  pool_size: String.to_integer(System.get_env("POOL_SIZE") || "2")

host = System.get_env("HOSTNAME")

config :not_spotify, :files,
  uploads_dir: Path.expand("../priv/uploads", __DIR__),
  host: [scheme: "https", host: host, port: 443],
  server_ip: "0.0.0.0",
  hostname: host,
  transport_opts: []
